FROM node:15.8.0-alpine3.10
RUN npm install -g @vue/cli@4.5.11

WORKDIR /home/codekids-class


# npm instll on vue project
COPY ./codekids-class/package*.json ./
RUN npm install

# copy files
COPY ./codekids-class .


CMD ["npm","run","build"]